### ISSUE TITLE
Using Oauth2.Builder gives NoSuchMethodError for com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.<init>

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#894]
_From [casper...@gmail.com](https://code.google.com/u/116200220836813895971/) on July 14, 2014 00:07:59_

Version of google-api-java-client (e.g. 1.15.0-rc)? 1.17.0-rc Java environment (e.g. Java 6, Android 2.3, App Engine)? Java 6 Describe the problem. After Upgrading from 1.13 to 1.17 I got this issue when using the Oauth2.Builder to get the user info How would you expect it to be fixed? Is something that has to be done different in the flow? I couldn't figure what

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=894_
